mansrht/blueprints/create.py
from flask import Blueprint, render_template, abort, request, redirect
from srht.database import db
from srht.flask import session
from srht.oauth import current_user, loginrequired
from srht.validation import Validation
from mansrht.repo import GitsrhtBackend
from mansrht.types import Wiki, WikiVisibility
from mansrht.wikis import validate_name, create_repo, create_wiki
from collections import namedtuple
import os

ListItem = namedtuple("ListItem", ["name", "url"])
create = Blueprint('create', __name__)

def select_repo(backend, wiki_name, wiki_visibility, **kwargs):
    repos = [
        ListItem(repo["name"], backend.get_repo_url(repo["name"]))
        for repo in backend.get_repos()
    ]

    existing = [
        wiki.repo.name
        for wiki in Wiki.query.filter(Wiki.owner_id == current_user.id).all()
        if wiki.repo
    ]

    # TODO: Add cancel button.
    return render_template(
            "select.html", typename="repo", typename_pretty="repo",
            default=wiki_name, default_visibility=wiki_visibility,
            items=sorted(repos, key=lambda x: x.name),
            existing=existing, **kwargs)

def select_ref(backend, wiki_name, repo_name, repo_visibility, new_repo, **kwargs):
    refs = []
    if not new_repo:
        try:
            refs = [ref for ref in backend.get_refs(repo_name)]
        except:
            abort(500)
    if refs:
        refs = [ListItem(
            os.path.split(ref["name"])[1],
            backend.get_ref_url(repo_name, ref["name"])) for ref in refs]

    # TODO: Add cancel button.
    return render_template(
            "select.html", typename="ref", typename_pretty="ref",
            default="wiki", items=sorted(refs, key=lambda x: x.name), **kwargs)

@create.route("/wiki/create")
@loginrequired
def create_GET():
    is_root = session.get("configure_root", False)
    return render_template("create.html", is_root=is_root)

@create.route("/wiki/create", methods=["POST"])
@loginrequired
def create_POST():
    valid = Validation(request)
    wiki_name = valid.require("name", friendly_name="Name")
    if not valid.ok:
        return render_template("create.html", **valid.kwargs)
    validate_name(valid, current_user, wiki_name)
    if not valid.ok:
        return render_template("create.html", **valid.kwargs)
    visibility = valid.optional("visibility",
            default="public",
            cls=WikiVisibility)
    session["wiki_name"] = wiki_name
    session["wiki_visibility"] = visibility.name
    return redirect("/wiki/create/repo")

@create.route("/wiki/create/repo")
@loginrequired
def select_repo_GET():
    wiki_name = session.get("wiki_name")
    wiki_visibility = session.get("wiki_visibility")
    if not wiki_name:
        return redirect("/wiki/create")
    backend = GitsrhtBackend(current_user)
    return select_repo(backend, wiki_name, wiki_visibility)

@create.route("/wiki/create/repo", methods=["POST"])
@create.route("/wiki/create/repo/new", methods=["POST"])
@loginrequired
def select_repo_POST():
    valid = Validation(request)
    repo_name = valid.require("repo", friendly_name="Repo")
    # will not be set (and does not matter) if existing repo selected
    repo_visibility = valid.optional("visibility",
            default="public")
    if not valid.ok:
        backend = GitsrhtBackend(current_user)
        wiki_name = session.get("wiki_name")
        visibility = session.get("wiki_visibility")
        return select_repo(backend, wiki_name, visibility, **valid.kwargs)

    # The repo name is checked at the end of the form.
    session["wiki_repo"] = (repo_name, repo_visibility, request.path.endswith("new"))
    return redirect("/wiki/create/ref")

@create.route("/wiki/create/ref")
@loginrequired
def select_ref_GET():
    wiki_name = session.get("wiki_name")
    wiki_repo = session.get("wiki_repo")
    if not wiki_name or not wiki_repo:
        session.pop("wiki_name", None)
        session.pop("wiki_repo", None)
        return redirect("/wiki/create")

    backend = GitsrhtBackend(current_user)
    repo_name, repo_visibility, new_repo = wiki_repo
    return select_ref(backend, wiki_name, repo_name, repo_visibility, new_repo)

@create.route("/wiki/create/ref", methods=["POST"])
@create.route("/wiki/create/ref/new", methods=["POST"])
@loginrequired
def select_ref_POST():
    wiki_name = session.get("wiki_name")
    wiki_repo = session.get("wiki_repo")
    if not wiki_name or not wiki_repo:
        session.pop("wiki_name", None)
        session.pop("wiki_repo", None)
        return redirect("/wiki/create")

    is_root = session.get("configure_root", False)
    visibility = WikiVisibility(session.get("wiki_visibility", "public"))
    repo_name, repo_visibility, new_repo = wiki_repo
    backend = GitsrhtBackend(current_user)

    valid = Validation(request)
    ref_name = valid.require("ref", friendly_name="Ref")
    if not valid.ok:
        return select_ref(backend, wiki_name, repo_name,
                repo_visibility, new_repo, **valid.kwargs)

    repo_dict = backend.get_repo(repo_name)
    if new_repo:
        # Check if a repo with the same name already exists.
        # If it does, we treat it as an error.
        valid.expect(
                repo_dict is None,
                "Repository already exists.",
                field="repo")
        if not valid.ok:
            return select_repo(backend, wiki_name, visibility, **valid.kwargs)
        repo_dict = backend.create_repo(repo_name, repo_visibility)

    # Try to find the latest commit if we're using an existing repo + ref.
    new_ref = request.path.endswith("new")
    commit = None
    if not new_repo and not new_ref:
        commit = backend.get_latest_commit(repo_name, ref_name)
        valid.expect(
                commit is not None,
                "Ref was not found.",
                field="ref")
    if not valid.ok:
        return select_ref(backend, wiki_name, repo_name,
                repo_visibility, new_repo, **valid.kwargs)

    backend.ensure_repo_update()

    repo = create_repo(
            new_repo, repo_dict["name"], repo_dict["id"], ref_name,
            current_user, commit=commit)
    create_wiki(
            valid, current_user, wiki_name,
            repo, visibility, is_root=is_root)

    del session["wiki_name"]
    del session["wiki_repo"]
    session.pop("wiki_visibility", None)
    session.pop("configure_root", None)

    return redirect("/{}/{}".format(current_user.canonical_name, wiki_name))

mansrht/blueprints/manage.py
from flask import Blueprint, render_template, abort, request, redirect, url_for
from srht.database import db
from srht.oauth import loginrequired
from srht.validation import Validation
from mansrht.access import UserAccess, check_access
from mansrht.repo import GitsrhtBackend
from mansrht.types import WikiVisibility
from mansrht.wikis import delete_wiki, is_root_wiki

manage = Blueprint('manage', __name__)

@manage.route("/manage/<owner_name>/<wiki_name>/info")
@loginrequired
def info(owner_name, wiki_name):
    owner, wiki = check_access(owner_name, wiki_name, UserAccess.manage)
    is_root = is_root_wiki(wiki)
    backend = GitsrhtBackend(owner)
    return render_template(
            "info.html", owner=owner, wiki=wiki, backend=backend,
            is_root=is_root)

@manage.route("/manage/<owner_name>/<wiki_name>/info", methods=["POST"])
@loginrequired
def info_POST(owner_name, wiki_name):
    owner, wiki = check_access(owner_name, wiki_name, UserAccess.manage)
    valid = Validation(request)
    visibility = valid.optional("visibility",
            cls=WikiVisibility,
            default=wiki.visibility)
    wiki.visibility = visibility
    db.session.commit()
    return redirect(url_for(
        "manage.info", owner_name=owner_name, wiki_name=wiki_name))

@manage.route("/manage/<owner_name>/<wiki_name>/delete")
@loginrequired
def delete(owner_name, wiki_name):
    # check_access() guarantees owner and wiki are valid.
    owner, wiki = check_access(owner_name, wiki_name, UserAccess.manage)
    return render_template(
            "delete.html", owner=owner, wiki=wiki,
            # Fill default value for "delete repo" option based-on if the
            # wiki was created with a new repo in the first place.
            delete_repo=wiki.repo.new)

@manage.route("/manage/<owner_name>/<wiki_name>/delete", methods=["POST"])
@loginrequired
def delete_POST(owner_name, wiki_name):
    valid = Validation(request)
    delete_repo = valid.optional("delete_repo")

    # check_access() guarantees owner and wiki are valid.
    owner, wiki = check_access(owner_name, wiki_name, UserAccess.manage)
    backend = GitsrhtBackend(owner)
    try:
        backend.unensure_repo_postupdate(wiki.repo)
    except:
        pass # Deleted, presumably
    delete_wiki(wiki, owner, delete_repo == "on")
    return redirect("/")

mansrht/blueprints/public.py
from flask import Blueprint, render_template, abort, request
from srht.flask import paginate_query
from srht.search import search_by
from srht.oauth import current_user
from mansrht.types import User, Wiki, WikiVisibility

public = Blueprint('public', __name__)


@public.route("/~<username>")
@public.route("/~<username>/")
def user_index(username):
    user = User.query.filter(User.username == username).first()
    if not user:
        abort(404)
    terms = request.args.get("search")
    wikis = Wiki.query.filter(Wiki.owner_id == user.id)
    if current_user and current_user.id != user.id:
        wikis = wikis.filter(Wiki.visibility == WikiVisibility.public)
    elif not current_user:
        wikis = wikis.filter(Wiki.visibility == WikiVisibility.public)

    search_error = None
    try:
        wikis = search_by(wikis, terms, [Wiki.name])
    except ValueError as ex:
        search_error = str(ex)

    wikis = wikis.order_by(Wiki.updated.desc())
    wikis, pagination = paginate_query(wikis)

    return render_template("user.html", user=user, wikis=wikis,
        search=terms, search_error=search_error, **pagination)

mansrht/templates/content.html
{% extends "man.html" %}
{% block title %}
{% if title %}
<title>{{ title }} - {{domain}}</title>
{% else %}
<title>{{domain}}</title>
{% endif %}
{% endblock %}
{% block content %}
{% if not is_root or len(path) != 0 %}
<div class="header-tabbed">
  <div class="container">
    <ul class="nav nav-tabs">
      <h2>
          {{title}}
      </h2>
      <li class="nav-item">
        <a
          class="nav-link active"
          href="{{ url_for("html.user_content",
            owner_name=wiki.owner.username, wiki_name=wiki.name) }}"
        >article</a>
      </li>
      <li class="nav-item">
        <a
          class="nav-link"
          href="{{web_url}}/tree/{{repo.ref}}/{{'/'.join(path)}}?view-source"
        >source</a>
      </li>
      <li class="nav-item">
        <a
          class="nav-link"
          href="{{web_url}}/log/{{repo.ref}}"
        >history</a>
      </li>
    </ul>
  </div>
</div>
{% if wiki and not is_root %}
<div class="header-extension">
  <div class="container">
    <a href="{{ url_for("public.user_index",
       username=wiki.owner.username) }}"
    >{{wiki.owner.canonical_name}}</a>/<wbr><a
       href="{{ url_for("html.user_content",
       owner_name=wiki.owner.username, wiki_name=wiki.name) }}"
    >{{wiki.name}}</a>
  </div>
</div>
{% endif %}
{% endif %}
<div class="container">
  <div class="content">
    {{ firstpara }}
  </div>
</div>
{% if frontmatter.get("toc", True) and len(toc) != 0 %}
<div class="container">
  <div class="event-list row">
    <div class="event toc col-md-12">
      <h3>Table of Contents</h3>
      <ol>
        {% macro toc_entry(entry, depth) %}
        <li>
          <a href="#{{ entry.id }}">{{ entry.name }}</a>
          {% if len(entry.children) > 0 %}
          <ul style="list-style: none; padding-left: {{ depth + 1 }}rem">
            {% for child in entry.children %}
              {{ toc_entry(child, depth + 1) }}
            {% endfor %}
          </ul>
          {% endif %}
        </li>
        {% endmacro %}
        {% for entry in toc %}
          {{ toc_entry(entry, 0) }}
        {% endfor %}
      </ol>
      {# TODO
      <div class="pull-right" style="margin-bottom: 1rem">
        <a href="#">Edit page</a>
      </div>
      #}
    </div>
  </div>
</div>
{% endif %}
<div class="container" style="flex-grow: 1">
  <div class="content">
    {{ content }}
  </div>
</div>
<div class="container">
  <h3>About this wiki</h3>
  <div class="row">
    <div class="col-md-8">
      <pre>commit <a
href="{{web_url}}/commit/{{repo.commit_sha}}"
>{{ repo.commit_sha }}</a>
Author: {{ repo.commit_author }} &lt;{{ repo.commit_email }}&gt;
Date:   {{ repo.commit_time }}

{{ repo.commit_message.rstrip("\n") }}</pre>
      <dl>
        <dt><strong>Clone this wiki</strong></dt>
        <dd>
        {% for url in clone_urls|map(attribute="url") %}
          {% if "://" in url %}
          <a href={{ url }}>{{ url }}</a>
          <span class="text-muted pull-right">(read-only)</span><br />
          {% else %}
          {{url}}
          <span class="text-muted pull-right">(read/write)</span><br />
          {% endif %}
        {% endfor %}
        </dd>
      </dl>
    </div>
    <div class="col-md-4">
      {% if current_user %}
        {% if is_root %}
        <a
          href="{{ url_for("create.create_GET") }}"
          class="btn btn-primary btn-block"
        >Create a wiki {{icon("caret-right")}}</a>
        {% endif %}
        {% if wiki and wiki.owner.username == current_user.username %}
        <a
          href="{{ url_for("manage.info",
            owner_name=wiki.owner.canonical_name, wiki_name=wiki.name) }}"
          class="btn btn-default btn-block"
        >Settings for this wiki {{icon('caret-right')}}</a>
        {% endif %}
        <a
          href="{{ url_for("public.user_index",
            username=current_user.username) }}"
          class="btn btn-default btn-block"
        >Browse your wikis {{icon('caret-right')}}</a>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

mansrht/templates/create.html
{% extends "man.html" %}
{% block title %}
<title>create wiki - {{domain}}</title>
{% endblock %}
{% block content %}
<div class="container">
  <div class="row">
    <section class="col-md-6">
      {% if is_root %}
      <h3 id="create">Create root wiki</h3>
      {% else %}
      <h3 id="create">Create new wiki</h3>
      {% endif%}
      <form method="POST" action="/wiki/create">
        {{csrf_token()}}
        <div class="form-group">
          <label for="name">Name</label>
          <input
            type="text"
            name="name"
            id="name"
            class="form-control {{valid.cls("name")}}"
            value="{{ repo_name or "" }}" />
          {{valid.summary("name")}}
        </div>
        {% if not is_root %}
        <fieldset class="form-group">
          <legend>Visibility</legend>
          <div class="form-check form-check-inline">
            <label
              class="form-check-label"
              title="Publically visible and listed on your profile"
            >
              <input
                class="form-check-input"
                type="radio"
                name="visibility"
                value="public"
                checked> Public
            </label>
          </div>
          <div class="form-check form-check-inline">
            <label
                class="form-check-label"
                title="Visible to anyone with the link, but not shown on your profile"
              >
              <input
                class="form-check-input"
                type="radio"
                name="visibility"
                value="unlisted"> Unlisted
            </label>
          </div>
          <div class="form-check form-check-inline">
            <label
              class="form-check-label"
              title="Only visible to you and your collaborators"
            >
              <input
                class="form-check-input"
                type="radio"
                name="visibility"
                value="private"> Private
            </label>
          </div>
        </fieldset>
        {% endif %}
        <button type="submit" class="btn btn-primary">
          Select repo {{icon("caret-right")}}
        </button>
      </form>
    </section>
  </div>
</div>
{% endblock %}

mansrht/templates/delete.html
{% extends "manage.html" %}
{% block content %}
<div class="row">
  <div class="col-md-12">
    <p>This will permanently delete the wiki.
      <strong>{{ owner.canonical_name }}/{{ wiki.name }}</strong>.
      This cannot be undone.
    </p>
    <form method="POST">
      {{csrf_token()}}
      <button type="submit" class="btn btn-danger">
        Proceed and delete {{icon("caret-right")}}
      </button>
      <a
        class="btn btn-default"
        href="{{ url_for("html.user_content",
          owner_name=owner.username, wiki_name=wiki.name) }}"
      >Nevermind</a>
      <label class="form-check-label" style="margin-left: 2rem">
        <input
          class="form-check-input"
          type="checkbox"
          name="delete_repo"
          style="position: relative; top: 2px;"
          {% if delete_repo %}
          checked
          {% endif %}> Delete corresponding repo?
      </label>
    </form>
{% endblock %}

mansrht/templates/index.html
{% extends "man.html" %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <p>
        You're seeing this page because the admin has not configured the
        default wiki yet. If you are an admin, ensure you are logged-in,
        then you will be guided through the configuration.
      </p>
      <p>Set the contents of the home page by writing <code>index.md</code>.</p>
    </div>
  </div>
</div>
{% endblock %}

mansrht/templates/info.html
{% extends "manage.html" %} {% block content %}
<div class="row">
  <div class="col-md-6">
  {% if is_root %}
    <p>
    Visit
    {% set repo_url = backend.get_repo_url(wiki.repo.name) %}
    <a
      href="{{ repo_url }}/settings/info"
      target="_blank"
      rel="noopener">{{ repo_url }}/settings/info</a>
    to control visibility of the backing repo for the root wiki.
    </p>
  {% else %}
    <form method="POST">
      {{csrf_token()}}
      <fieldset class="form-group">
        <div class="form-check form-check-inline">
          <label
            class="form-check-label"
            title="Publically visible and listed on your profile"
          >
            <input
              class="form-check-input"
              type="radio"
              name="visibility"
              value="public"
              {{ "checked" if wiki.visibility.value == "public" else "" }}
            > Public
          </label>
        </div>
        <div class="form-check form-check-inline">
          <label
              class="form-check-label"
              title="Visible to anyone with the link, but not shown on your profile"
            >
            <input
              class="form-check-input"
              type="radio"
              name="visibility"
              value="unlisted"
              {{ "checked" if wiki.visibility.value == "unlisted" else "" }}
            > Unlisted
          </label>
        </div>
        <div class="form-check form-check-inline">
          <label
            class="form-check-label"
            title="Only visible to you and your collaborators"
          >
            <input
              class="form-check-input"
              type="radio"
              name="visibility"
              value="private"
              {{ "checked" if wiki.visibility.value == "private" else "" }}
            > Private
          </label>
        </div>
      </fieldset>
      <p>
      Visiblity of the backing repo is controlled separately. To manage settings
      for your backing repo, visit
      {% set repo_url = backend.get_repo_url(wiki.repo.name) %}
      <a
        href="{{ repo_url }}/settings/info"
        target="_blank"
        rel="noopener">{{ repo_url }}/settings/info</a>.
      </p>
      <button type="submit" class="btn btn-primary pull-right">
        Save {{icon("caret-right")}}
      </button>
    </form>
  {% endif %}
  </div>
</div>
{% endblock %}

mansrht/templates/man.html
{% extends "layout.html" %}
{% block body %} 
{% block content %}{% endblock %}
{% endblock %}

mansrht/templates/manage.html
{% extends "layout.html" %}
{% block body %}
<!--
<h2>Wiki settings</h2>
<section>
  <p>
    You can manage settings for
    <strong>{{ owner.canonical_name }}/{{ wiki.name }}</strong> here.</p>
</section>
-->
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12 header-tabbed">
      <h2>
        {{ owner.canonical_name }}/<wbr>{{ wiki.name }}
      </h2>
      {% block tabs %}
      <ul class="nav nav-tabs">
        <li class="nav-item">
          <a class="nav-link" href="/{{ owner.canonical_name }}/{{ wiki.name }}">
            {{icon("caret-left")}} back
          </a>
        </li>
        <li class="nav-item">
          <a
            class="nav-link \
            {% if request.path.endswith("info") %}active{% endif %}"
            href="{{ url_for("manage.info",
              owner_name=owner.canonical_name, wiki_name=wiki.name) }}"
          >info</a>
        </li>
        <li class="nav-item">
          <a
            class="nav-link \
            {% if request.path.endswith("delete") %}active{% endif %}"
            href="{{ url_for("manage.delete",
              owner_name=owner.canonical_name, wiki_name=wiki.name) }}"
          >delete</a>
        </li>
      </ul>
      {% endblock %}
    </div>
  </div>
</div>
<div class="container">
  {% block content %}{% endblock %}
</div>
{% endblock %}

mansrht/templates/new-wiki.html
{% extends "man.html" %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <h1>index</h1>
      <p>
        Your wiki has been created, but does not have any content. To add
        content, push commits to the <strong>{{repo.ref}}</strong> branch of
        <a
          href="{{web_url}}"
        >{{wiki.owner.canonical_name}}/{{wiki.repo.name}}</a>:
        <code class="grey">{{clone_url.url}}</code>
      </p>
      {% if repo.ref != "master" %}
      <pre>git clone {{clone_url.url}} &amp;&amp; cd {{repo.name}}
git checkout --orphan {{repo.ref}}
git rm -rf *
echo "Hello world!" &gt;index.md
git add index.md
git commit -m"Initial wiki commit"
git push -u origin {{repo.ref}}</pre>
      {% else %}
      <pre>git clone {{clone_url.url}} &amp;&amp; cd {{repo.name}}
echo "Hello world!" &gt;index.md
git add index.md
git commit -m"Initial wiki commit"
git push -u origin master</pre>
      {% endif %}
      <p>
        For more information, consult the
        <a href="https://man.sr.ht/man.sr.ht/">documentation</a>.
      </p>
    </div>
    <div class="col-md-8">
      {% if wiki.owner.username == current_user.username %}
        <a
          href="{{ url_for("manage.info",
            owner_name=wiki.owner.canonical_name, wiki_name=wiki.name) }}"
          class="btn btn-default btn-block"
        >Settings for this wiki {{icon('caret-right')}}</a>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

mansrht/templates/oauth-error.html
{% extends "man.html" %}
{% block content %}
<div class="container">
  <h2>Error logging in</h2>
  <p>{{ details }}</p>
</div>
{% endblock %}

mansrht/templates/select.html
{% extends "layout.html" %}
{% block body %}
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <p>
        The content for each wiki is managed by a git.sr.ht repository. You can
        either create a new repo or choose an existing repo. A ref will also be
        needed. This can either be an existing head (if there are any), or you
        may optionally push to a new branch.
      </p>
    </div>
    <div class="col-md-8">
      <h3>Create a new {{ typename_pretty }}</h3>
        <form method="POST" action="/wiki/create/{{ typename }}/new">
          {{csrf_token()}}
          <div class="form-group">
            <label for="{{ typename }}">Name</label>
            <input
              type="text"
              name="{{ typename }}"
              id="name"
              class="form-control {{ valid.cls(typename) }}"
              value="{{ default or "" }}" />
            {{ valid.summary(typename) }}
          </div>

          {% if typename == "repo" %}
          <fieldset class="form-group">
            <legend>Visibility</legend>
            <div class="form-check form-check-inline">
              <label
                class="form-check-label"
                title="Publically visible and listed on your profile"
              >
                <input {{ "checked" if default_visibility.lower() == "public" }}
                  class="form-check-input"
                  type="radio"
                  name="visibility"
                  value="public"> Public
              </label>
            </div>
            <div class="form-check form-check-inline">
              <label
                  class="form-check-label"
                  title="Visible to anyone with the link, but not shown on your profile"
              >
                <input {{ "checked" if default_visibility.lower() == "unlisted" }}
                  class="form-check-input"
                  type="radio"
                  name="visibility"
                  value="unlisted"> Unlisted
              </label>
            </div>
            <div class="form-check form-check-inline">
              <label
                class="form-check-label"
                title="Only visible to you and your collaborators"
              >
                <input {{ "checked" if default_visibility.lower() == "private" }}
                  class="form-check-input"
                  type="radio"
                  name="visibility"
                  value="private"> Private
              </label>
            </div>
          </fieldset>
          {% endif %}

          <button type="submit" class="btn btn-primary">
            Create {{ typename_pretty }} {{ icon("caret-right") }}
          </button>
        </form>
      {% if items %}
      <h3>Or choose an existing {{ typename_pretty }}</h3>
        <form>
          <input
            name="search"
            type="text"
            placeholder="Search your {{ typename_pretty }}s"
            class="form-control"
            value="{{ search if search else "" }}" />
        </form>

        <div class="event-list configure">
        {% for item in items %}
          <form class="event" method="POST" action="/wiki/create/{{ typename }}">
            {{csrf_token()}}
            <input type="hidden" name="{{ typename }}" value="{{ item.name }}" />
            <h4>
              <a
                href="{{ item.url }}"
                target="_blank"
                rel="noopener"
              >{{ item.name }}</a>
            </h4>
            {% if typename != "repo" or item.name not in existing %}
            <button
              type="submit"
              class="btn btn-primary btn-lg"
            >Select {{ typename_pretty }} {{ icon("caret-right") }}</button>
            {% else %}
            <button
              class="pull-right btn btn-default btn-lg"
              disabled
            >Already created</button>
            {% endif %}
          </form>
        {% endfor %}
      </div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

mansrht/templates/user.html
{% extends "man.html" %}

{% block content %}
<div class="container">
  <div class="row">
    <section class="col-md-4">
      <h2>
        ~{{ user.username }}
      </h2>
      {% if user.location %}
      <p>{{user.location}}</p>
      {% endif %}
      {% if user.url %}
      <p>
        <a
          href="{{user.url}}"
          target="_blank"
          rel="me noopener noreferrer nofollow"
        >{{user.url}}</a>
      </p>
      {% endif %}
      {% if user.bio %}
      {{user.bio | md}}
      {% endif %}
      {% if current_user and current_user.username == user.username %}
      <a
        href="{{url_for('create.create_GET')}}"
        class="btn btn-primary btn-block"
      >Create new wiki {{icon("caret-right")}}</a>
      {% endif %}
      {% if notice %}
      <div class="alert alert-success">
        {{ notice }}
      </div>
      {% endif %}
    </section>
    <section class="col-md-8">
      {% if len(wikis) == 0 %}
      {% if search %}
      <form>
        <input
          name="search"
          type="text"
          placeholder="Search"
          class="form-control"
          value="{{ search if search else "" }}" />
      </form>
      <p>Nothing found.</p>
      {% else %}
      <p>This user has no wikis.</p>
      {% endif %}
      {% else %}
      <form>
        <input
          name="search"
          type="text"
          placeholder="Search"
          class="form-control{% if search_error %} is-invalid{% endif %}"
          value="{{ search if search else "" }}" />
        {% if search_error %}
          <div class="invalid-feedback">{{ search_error }}</div>
        {% endif %}
      </form>
      <div class="event-list">
        {% for wiki in wikis %}
        <div class="event">
          <h4>
            <a href="/~{{user.username}}/{{wiki.name}}">
              ~{{user.username}}/{{wiki.name}}
            </a>
            {% if wiki.visibility.value != 'public' %}
            <small class="pull-right">
              {{ wiki.visibility.value }}
            </small>
            {% endif %}
          </h4>
          <p>
          </p>
        </div>
        {% endfor %}
      </div>
      {% endif %}
      {{ pagination() }}
    </section>
  </div>
</div>
{% endblock %}